logsToConsole: false

# Максимальное количество сущностей на один чанк
maxEntitiesChunk: 20
# Максимальное количество сущностей на 3x3 чанка
maxEntities: 30

checkerTPS: true

messages:
  noPermission: 'У вас нет прав на использование этой команды.'

prices:
  coloredNickname:
    cost: 100
    sales: false
    salesCosts: 100
  addPower:
    cost: 100
    sales: false
    salesCosts: 100
  particleMenu:
    cost: 200
    sales: false
    salesCosts: 200
  sponsor:
    cost: 500
    sales: false
    salesCosts: 500

banwords: ["негр", "негра", "пдр", "вдул", "охуел", "гей", "геи", "даун", "дауны", "куколд", "cuckold", "пизда", "сunt", "инцел", "incel", "симп", "simp", "девственник", "virgin", "retard", "ретард", "дебил", "жид", "хач", "хохол", "гомик", "педик", "пидорас", "faggot", "нага", "ниггер", "naga", "nigga", "хиджаб", "хачи", "хача", "жидов", "жиды", "русня", "русню", "хохлов", "отсталый", "калека", "шизик", "аутист", "даун", "пидарас", "хохлы", "нига", "конча", "nigger", "niga", "pidor", "нигер", "пидор", "шлюха", "пидр", "pidr", "pdr", "чурк"]
fakebanwords: ["книг", "кончаются", "кончается", "хачу", "спидран"]

# Discord webhook URL for report system
webhookURL: "url"

# Do not change this value
ConfigVersion: 1
