logsToConsole: false

# Максимальное количество сущностей на один чанк
maxEntitiesChunk: 20
# Максимальное количество сущностей на 3x3 чанка
maxEntities: 30

checkerTPS: true

messages:
  noPermission: 'У вас нет прав на использование этой команды.'

prices:
  coloredNickname:
    cost: 100
    sales: false
    salesCosts: 100
  addPower:
    cost: 100
    sales: false
    salesCosts: 100
  particleHats:
    cost: 200
    sales: false
    salesCosts: 200
  sponsor:
    cost: 500
    sales: false
    salesCosts: 500

# Do not change this value
ConfigVersion: 1
